#!/usr/bin/env python
#A command-line google search tool
import webbrowser
import optparse
import os

def main():
    usage="usage: %prog [options] args"
    p=optparse.OptionParser()
    p.add_option("--search", "-s", help="The search term.", default="")
    options, arguments=p.parse_args()
    search_term=options.search
    url="http://www.google.com/search?q="+search_term.replace(" ", "+")+"&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a"
    #Open Page
    ShowResults=webbrowser.open(url)

if __name__ == '__main__':
    main()
