#!/usr/bin/env python
#A program to check if there are any updates available for Arch
from subprocess import Popen,PIPE
import os

def main():
    p=Popen("pacman -Qu|grep Targets|cut --delimiter=\" \" -f 2|sed -e 's/(//' -e 's/)://'",shell=True,stdout=PIPE)
    x=p.stdout.read()
    if x != "":
        tally=int(x)
        if tally == "1":
             print "1 package to update"
        else:
             print "%s packages to update" % str(tally)
    else:
        print "No packages to update"

if __name__ == '__main__':
    main()
