#!/bin/bash

#read in arguments
args=("$@")

if [ "${args[0]}" != "" ]; then
    convert ${args[0]} \
          -bordercolor white  -border 6 \
          -bordercolor grey60 -border 1 \
          -background  none   -rotate 6 \
          -background  black  \( +clone -shadow 60x4+4+4 \) +swap \
          -background  none   -flatten \
          -depth 8  -quality 100   ${args[1]}
else
    echo "Invalid arguments, please run this script with \"polaroidConv <input> <output>\""
fi
